# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Game(object):
    def setupUi(self, Game):
        Game.setObjectName(_fromUtf8("Game"))
        Game.resize(310, 665)
        self.label_2 = QtGui.QLabel(Game)
        self.label_2.setGeometry(QtCore.QRect(10, 280, 291, 41))
        self.label_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_2.setStyleSheet(_fromUtf8("label_2 =rgb(118, 140, 19)"))
        self.label_2.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_2.setFrameShadow(QtGui.QFrame.Raised)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_12 = QtGui.QPushButton(Game)
        self.pushButton_12.setGeometry(QtCore.QRect(200, 610, 110, 51))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_10 = QtGui.QPushButton(Game)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 610, 110, 51))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_11 = QtGui.QPushButton(Game)
        self.pushButton_11.setGeometry(QtCore.QRect(100, 610, 110, 51))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.toolButton = QtGui.QToolButton(Game)
        self.toolButton.setGeometry(QtCore.QRect(10, 0, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(61)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.toolButton.setFont(font)
        self.toolButton.setText(_fromUtf8(""))
        self.toolButton.setAutoRepeat(False)
        self.toolButton.setAutoRepeatDelay(321)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.toolButton_2 = QtGui.QToolButton(Game)
        self.toolButton_2.setGeometry(QtCore.QRect(110, 0, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(63)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setText(_fromUtf8(""))
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.toolButton_3 = QtGui.QToolButton(Game)
        self.toolButton_3.setGeometry(QtCore.QRect(210, 0, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(63)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setText(_fromUtf8(""))
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.toolButton_4 = QtGui.QToolButton(Game)
        self.toolButton_4.setGeometry(QtCore.QRect(10, 90, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(63)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setText(_fromUtf8(""))
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.toolButton_5 = QtGui.QToolButton(Game)
        self.toolButton_5.setGeometry(QtCore.QRect(110, 90, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(63)
        self.toolButton_5.setFont(font)
        self.toolButton_5.setText(_fromUtf8(""))
        self.toolButton_5.setObjectName(_fromUtf8("toolButton_5"))
        self.toolButton_6 = QtGui.QToolButton(Game)
        self.toolButton_6.setGeometry(QtCore.QRect(210, 90, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(63)
        self.toolButton_6.setFont(font)
        self.toolButton_6.setText(_fromUtf8(""))
        self.toolButton_6.setObjectName(_fromUtf8("toolButton_6"))
        self.toolButton_7 = QtGui.QToolButton(Game)
        self.toolButton_7.setGeometry(QtCore.QRect(10, 180, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(63)
        self.toolButton_7.setFont(font)
        self.toolButton_7.setText(_fromUtf8(""))
        self.toolButton_7.setObjectName(_fromUtf8("toolButton_7"))
        self.tabWidget = QtGui.QTabWidget(Game)
        self.tabWidget.setGeometry(QtCore.QRect(10, 380, 291, 231))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.plainTextEdit_4 = QtGui.QPlainTextEdit(self.tab)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(0, 60, 281, 141))
        self.plainTextEdit_4.setReadOnly(True)
        self.plainTextEdit_4.setPlainText(_fromUtf8(""))
        self.plainTextEdit_4.setObjectName(_fromUtf8("plainTextEdit_4"))
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(2, 0, 281, 51))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 0, 281, 201))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.plainTextEdit_5 = QtGui.QPlainTextEdit(self.tab_5)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(3, 0, 281, 201))
        self.plainTextEdit_5.setReadOnly(True)
        self.plainTextEdit_5.setObjectName(_fromUtf8("plainTextEdit_5"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.toolButton_8 = QtGui.QToolButton(Game)
        self.toolButton_8.setGeometry(QtCore.QRect(110, 180, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(63)
        self.toolButton_8.setFont(font)
        self.toolButton_8.setText(_fromUtf8(""))
        self.toolButton_8.setObjectName(_fromUtf8("toolButton_8"))
        self.toolButton_9 = QtGui.QToolButton(Game)
        self.toolButton_9.setGeometry(QtCore.QRect(210, 180, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(63)
        self.toolButton_9.setFont(font)
        self.toolButton_9.setText(_fromUtf8(""))
        self.toolButton_9.setObjectName(_fromUtf8("toolButton_9"))
        self.line = QtGui.QFrame(Game)
        self.line.setGeometry(QtCore.QRect(10, 260, 291, 21))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(Game)
        self.line_2.setGeometry(QtCore.QRect(10, 320, 291, 21))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.radioButton = QtGui.QRadioButton(Game)
        self.radioButton.setGeometry(QtCore.QRect(30, 340, 111, 31))
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(Game)
        self.radioButton_2.setGeometry(QtCore.QRect(170, 340, 97, 31))
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))

        self.retranslateUi(Game)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Game)

    def retranslateUi(self, Game):
        Game.setWindowTitle(_translate("Game", "TicTacToe", None))
        self.pushButton_12.setText(_translate("Game", "Exit", None))
        self.pushButton_10.setText(_translate("Game", "Send", None))
        self.pushButton_11.setText(_translate("Game", "Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Game", "Massaging", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Game", "Event Loger", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Game", "Game Loger", None))
        self.radioButton.setText(_translate("Game", "Encrypte Data", None))
        self.radioButton_2.setText(_translate("Game", "Normal Data", None))

